#!/usr/bin/env bash
# bash script that displays `To infinity and beyond` indefinitely
# a `sleep 2` is added in between each iteration

while true
do
	echo "To infinity and beyond"

	sleep 2	# `sleep 2` added in between each iteration
done
