#!/usr/bin/env bash
# displays "Best School" until ninth time, display "Hi", and then "Best School"

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
