#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts my_hosts

sed -i s/^127.*/"127.0.0.2 localhost"/ my_hosts

echo "8.8.8.8 facebook.com" >> my_hosts

cp my_hosts /etc/hosts
